name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocr_backend: [ocrmypdf]
        merge_backend: [pymupdf]
    env:
      OCR_BACKEND: ${{ matrix.ocr_backend }}
      MERGE_BACKEND: ${{ matrix.merge_backend }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set Poetry to use Python 3.9
        run: |
          python3.9 --version
          poetry env use python3.9

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ocrmypdf

      - name: Install dependencies
        run: poetry install --with dev

      - name: Lint
        run: poetry run ruff outlook_exporter tests

      - name: Test
        run: poetry run pytest -q
