name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Lint
        run: poetry run ruff outlook_exporter tests
      - name: Test
        run: poetry run python -m pytest -q
